#ifndef SHAKTI_CONFIG_H
#define SHAKTI_CONFIG_H

#define SHAKTI_EDEN_FACTS_PATH "data/eden/eden_facts.txt"
#define SHAKTI_EDEN_THESAURUS_PATH "data/eden/thesaurus.txt"
#define SHAKTI_EDEN_STREAM_PATH "data/eden/eden_stream.log"
#define SHAKTI_LEARNED_STREAM_PATH "data/learned/learned_stream.log"
#define SHAKTI_EVIDENCE_PATH "data/learned/evidence.log"
#define SHAKTI_SCHOOL_PATH "data/school/school_state.log"
#define SHAKTI_EDEN_MANIFEST_PATH "data/eden/manifest.xml"
#define SHAKTI_EDEN_LEDGER_PATH "data/eden/manifest_ledger.tsv"

#define SHAKTI_GOAL_PATH "data/control/goal.txt"
#define SHAKTI_NOTEBOOK_PATH "data/control/notebook.log"
#define SHAKTI_MENU_PATH "data/control/menu.txt"
#define SHAKTI_MESSAGES_PATH "data/control/messages.log"
#define SHAKTI_REFLECTION_PATH "data/control/reflections.log"
#define SHAKTI_STARTUP_REPORT_PATH "data/control/startup_report.txt"

#define SHAKTI_MAX_FACTS 512U
#define SHAKTI_MAX_SYNONYMS 256U
#define SHAKTI_MAX_EVIDENCE 512U
#define SHAKTI_WORKING_SLOTS 64U
#define SHAKTI_SHORT_TERM_SLOTS 64U
#define SHAKTI_MAX_LOCKED_BLOCKS 16U
#define SHAKTI_MAX_TABLET_STONES 128U
#define SHAKTI_MAX_MANIFEST_LEVELS 16U
#define SHAKTI_MAX_MANIFEST_TABLETS 256U

#define SHAKTI_INPUT_CAPACITY 1024U
#define SHAKTI_TEXT_CAPACITY 256U
#define SHAKTI_LONG_TEXT_CAPACITY 4096U
#define SHAKTI_QUESTION_CAPACITY 192U
#define SHAKTI_ANSWER_CAPACITY 96U
#define SHAKTI_RELATION_CAPACITY 48U
#define SHAKTI_SOURCE_CAPACITY 96U
#define SHAKTI_PATH_CAPACITY 512U
#define SHAKTI_KEY_CAPACITY 192U
#define SHAKTI_LEVEL_ID_CAPACITY 64U
#define SHAKTI_MODE_CAPACITY 32U
#define SHAKTI_STATE_CAPACITY 16U
#define SHAKTI_REQUIREMENTS_CAPACITY 256U
#define SHAKTI_TICK_CAPACITY 48U
#define SHAKTI_EVENT_ID_CAPACITY 80U
#define SHAKTI_LINE_CAPACITY 2048U
#define SHAKTI_MAX_TOKENS 32U
#define SHAKTI_TOKEN_CAPACITY 48U
#define SHAKTI_MAX_CREATIVE_CANDIDATES 8U
#define SHAKTI_MAX_SOUND_SEQUENCE_CLIPS 64U
#define SHAKTI_MENU_SECTION_CAPACITY 32U
#define SHAKTI_MENU_DESCRIPTION_CAPACITY 512U
#define SHAKTI_MAX_MENU_SECTIONS 16U

#define SHAKTI_FRAME_LIMIT 1000U
#define SHAKTI_DEFAULT_MASTERY_TARGET 10U
#define SHAKTI_ANSWER_SCORE 850U
#define SHAKTI_CAUTIOUS_SCORE 650U
#define SHAKTI_REQUIRED_MARGIN 120U
#define SHAKTI_REFLECTION_INTERVAL 10U
#define SHAKTI_REFLECTION_MAX_DEFERRALS 3U
#define SHAKTI_HEARTBEAT_MAX_MINUTES 30U

#endif
